module NewYorkAddressTerms

  BrooklynNames = ["bk","brooklyn","bklyn","dumbo","dumbonyc","downtownbklyn","fort green","ft green","williamsburg","park slope","carroll"]

  QueensNames = ["queens","astoria"]

  NewYorkStreetNames =
  [
    "albany",
    "allen",
    "amsterdam",
    "ann",
    "astor",
    "avenue a",
    "avenue b",
    "avenue c",
    "avenue d",
    "ave a",
    "ave b",
    "ave c",
    "ave d",
    "bank",
    "barclay",
    "barrow",
    "battery",
    "bayard",
    "beach",
    "beak",
    "bedford",
    "beekman",
    "bethune",
    "bleecker",
    "bogardus",
    "bowery",
    "broome",
    "broadway",
    "b'way",
    "bway",
    "broad",
    "bryant",
    "cabrini",
    "canal",
    "(?<!grand\s)central(?!\spark)",
    "centre",
    "chambers",
    "charles",
    "charlton",
    "christopher",
    "chrystie",
    "church",
    "crosby",
    "columbus",
    "cortlandt",
    "cortland",
    "delancey",
    "ditmars",
    "ditmas",
    "dover",
    "eldridge",
    "elizabeth",
    "end",
    "essex",
    "fdr",
    "fletcher",
    "forsyth",
    "fredrick douglas",
    "frederick douglas",
    "front",
    "fulton",
    "gay",
    "gold",
    "gouverneur",
    "gouveneur",
    "gouvener",
    "gramercy",
    "grand(?!\scentral)",
    "great jones",
    "greene",
    "greenwich",
    "grove",
    "henry",
    "hester",
    "horatio",
    "houston",
    "hudson",
    "jane",
    "jay",
    "jefferson",
    "john",
    "juan",
    "kenmare",
    "king",
    "lafayette",
    "laguardia",
    "lenox",
    "leroy",
    "lex",
    "lexington",
    "liberty",
    "ludlow",
    "macdougal",
    "madison",
    "maiden",
    "main",
    "mercer",
    "malcolm x",
    "monroe",
    "morton",
    "mott",
    "mulberry",
    "nassau",
    "old",
    "(?<!central\s)(?<!prospect\s)(?<!garvey\s)park(?!ed)",
    "pearl",
    "peck",
    "perry",
    "pioneer",
    "pitt",
    "prince",
    "rector",
    "richards",
    "riverside",
    "rivington",
    "rutgers",
    "saint james",
    "skillman",
    "smith",
    "st james",
    "saint marks",
    "st marks",
    "st mark",
    "saint nicholas",
    "st nicholas",
    "st nic",
    "saint nic",
    "spring",
    "stanton",
    "stuyvesant",
    "sullivan",
    "thompson",
    "trinity",
    "union",
    "vanderbilt",
    "vandam",
    "vandem",
    "varick",
    "vesey",
    "visitation",
    "washington",
    "wall",
    "warren",
    "water",
    "west",
    "white",
    "william",
    "wooster",
    "worth",
    "york",
    "chatham",
    "duffy",
    "hanover",
    "lincoln",
    "madison",
    "mad",
    "tompkins",
    "willoughby",
    "myrtle"
  ]

end