# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Truck.create(name: 'Comme Ci, Comme Ca', twitter_user_name: 'Chefsamirtruck')
Truck.create(name: 'Uncle Gussys', twitter_user_name: 'UncleGussys')
Truck.create(name: 'Korilla BBQ', twitter_user_name: 'KorillaBBQ')
Truck.create(name: 'Lukes Lobster Truck', twitter_user_name: 'LukesLobster')
Truck.create(name: 'The Cinnamon Snail', twitter_user_name: 'VeganLunchTruck')
Truck.create(name: 'Morris Grilled Cheese Truck', twitter_user_name: 'morristruck')
Truck.create(name: 'King Souvlaki', twitter_user_name: 'KingSouvlaki')
Truck.create(name: 'Luckyim Thai', twitter_user_name: 'luckyimthai')
Truck.create(name: 'The Steel Cart', twitter_user_name: 'TheSteelCart')
Truck.create(name: 'Mac Truck', twitter_user_name: 'mactruckny')
Truck.create(name: 'Red Hook Lobster Pound', twitter_user_name: 'lobstertruckny')
Truck.create(name: 'Patacon Pisao Truck', twitter_user_name: 'PataconPisaoNYC')
Truck.create(name: 'Mamu Thai Noodle', twitter_user_name: 'mamuthainoodle')
Truck.create(name: 'Wafels & Dinges Truck', twitter_user_name: 'waffletruck')
Truck.create(name: 'Moo Shu Grill', twitter_user_name: 'mooshugrill')
Truck.create(name: 'Cambodian Cuisine Torsu', twitter_user_name: 'CamCuisineTorsu')
Truck.create(name: 'Big Ds Grub', twitter_user_name: 'bigdsgrub')
Truck.create(name: 'Yankee Doodle Dandys', twitter_user_name: 'USAFoodTruck')
Truck.create(name: 'Bob and Jo Truck', twitter_user_name: 'bobjoTruck')
Truck.create(name: 'The GoGo Grill', twitter_user_name: 'TheGoGoGrill')
Truck.create(name: 'Sweet Chili', twitter_user_name: 'SweetChiliNYC')
Truck.create(name: 'Bian Dang Truck', twitter_user_name: 'biandangnyc')
Truck.create(name: 'Taim Mobile Falafel', twitter_user_name: 'TaimMobile')
Truck.create(name: 'Papaya King Truck', twitter_user_name: 'PapayaKingTruck')
Truck.create(name: 'Langos Truck', twitter_user_name: 'LangosTruck')
Truck.create(name: 'DiSOs Italian Sandwich', twitter_user_name: 'DiSOSNYC')
Truck.create(name: 'Domo Taco', twitter_user_name: 'DomoTaco')
Truck.create(name: 'Kimchi Taco', twitter_user_name: 'KimchiTruck')
Truck.create(name: 'The Taco Truck', twitter_user_name: 'TheTacoTruck')
Truck.create(name: 'Toast Monster', twitter_user_name: 'toastmonsternyc')
Truck.create(name: 'Old Traditional Polish Cuisine', twitter_user_name: 'PolishCuisine')
Truck.create(name: 'Shortys NYC', twitter_user_name: 'shortysnyc')
Truck.create(name: 'Schnitzel & Things', twitter_user_name: 'schnitznthings')
